### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by velmyshanovnyi** [velmyshanovnyi/ptrender#5]
**Describe the bug**
при запуску скрипта

**To Reproduce**

1. запускаю СМД
2. вставляю **node Z:\ptrender\render.js**
3. вилітає цей еррур

```
C:\Users\velmy>node Z:\ptrender\render.js
Read config template batch.pts.tpl
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'batch.pts.tpl'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at init (Z:\ptrender\render.js:99:19)
    at Object.<anonymous> (Z:\ptrender\render.js:104:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'batch.pts.tpl'
}

C:\Users\velmy>
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1027826/62254090-8d971800-b400-11e9-9575-fc99b0ae74cd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by velmyshanovnyi** [comment]
вже не вилітає цей еррур,
напевно повіксив вже...
